modLoader="javafml"
loaderVersion="[35,)"
#issueTrackerURL=""
license="MIT"

[[mods]]
modId="insane"
version="${file.jarVersion}"
displayName="Insane"
#displayURL=""
authors="Mrbysco, ShyNieke"
description='''
Does that make me crazy? Probably.
'''